name: Check Rate Limit

on:
  workflow_dispatch:
    
jobs:
  query:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v5

    - name: gh api query rate limit
      run: |
        gh api rate_limit
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
